=== Monica-R/DAW/LND/XML-DTD-XSL/Practica-03/carta.dtd
<!ELEMENT mensaje (remite,destinatario,asunto,texto)>
<!ELEMENT remite (nombre,email)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT destinatario (nombre-d,correo)>
<!ELEMENT nombre-d (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT texto (parrafo)>
<!ELEMENT parrafo (#PCDATA)>

=== Monica-R/DAW/LND/XML-DTD-XSL/Practica-03/carta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensaje SYSTEM "carta.dtd">
<mensaje>
  <remite>
    <nombre>Alfredo Reino</nombre>
    <email>alf@ibium.com</email>
  </remite>
  <destinatario>
    <nombre-d>Bill Clinton</nombre-d>
    <correo>president@whitehouse.gov</correo>
  </destinatario>
  <asunto>Hola Bill</asunto>
  <texto>
    <parrafo>¿Hola qué tal?</parrafo>
  </texto>
</mensaje>
