=== Monica-R/DAW/LND/XML-DTD-XSL/practica-001/ferreteria.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD para un documento XML que contiene una lista de pedidos de productos para ferreterÃ­as-->
<!ELEMENT ferreterias (ferreteria*)>
<!ELEMENT ferreteria (nombre, email?, pedido+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT pedido (idpedido,producto+)>
<!ELEMENT idpedido (#PCDATA)>
<!ELEMENT producto (idproducto,color,peso?)>
<!ELEMENT idproducto (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT peso (libras|kilos)>
<!ELEMENT libras (#PCDATA)>
<!ELEMENT kilos (#PCDATA)>

=== Monica-R/DAW/LND/XML-DTD-XSL/practica-001/ferreteria.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ferreterias SYSTEM "ferreteria.dtd">
<ferreterias xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ferreteria.xsd">
  <ferreteria>
    <nombre>Ferreterias Guanarteme</nombre>
    <email>ferrguanarteme@gmail.com</email>
    <pedido>
      <idpedido>T0025</idpedido>
      <producto>
        <idproducto>LPO697112</idproducto>
        <color>azul</color>
        <peso>
          <libras>89</libras>
        </peso>
      </producto>
      <idpedido>T0025</idpedido>
      <producto>
        <idproducto>LRT64127</idproducto>
        <color>verde</color>
        <peso>
          <kilos>100</kilos>
        </peso>
      </producto>
    </pedido>
  </ferreteria>
</ferreterias>
