<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE cv [
    <!ELEMENT cv (presentacion, (datos_academicos | experiencia_laboral)+, (lectura|deportes|otros)*, referencias*)>
    <!ELEMENT presentacion (#PCDATA)>
    <!ELEMENT datos_academicos (#PCDATA)>
    <!ELEMENT experiencia_laboral (#PCDATA)>
    <!ELEMENT lectura (#PCDATA)>
    <!ELEMENT deportes (#PCDATA)>
    <!ELEMENT otros (#PCDATA)>
    <!ELEMENT referencias (#PCDATA)>
]>

<cv>
    <presentacion></presentacion>
    <datos_academicos>
        Nombre: Paco
        Apellidos: Almeida
    </datos_academicos>
    <deportes>Surf</deportes>
    <deportes>Hockey</deportes>
    <deportes>Vela latina</deportes>
</cv>